# -*- coding: utf-8 -*-
"""DSP Cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZbizL3swRSL8e1dek8Xn6SZnI8CRw60K

# **EXPLORATORY DATA ANALYSIS** (RAW DATA)
"""

stations = pd.read_csv ('kuantan_ev_station.csv')
stations.head()

print(stations.columns)

print("Shape of the DataFrame:", stations.shape)
print("\nInformation about the DataFrame:")
stations.info()

print("\nDescriptive statistics of the DataFrame:")
stations.describe()

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Set style for better aesthetics
sns.set_style("whitegrid")

# Visualization 1: Distribution of Total Number of Chargers
plt.figure(figsize=(10, 6))
sns.histplot(stations['JUMLAH BILANGAN UNIT PENGECAS'], bins=5, kde=True)
plt.title('Distribution of Total Number of Chargers per Station (Raw Data)')
plt.xlabel('Total Number of Chargers')
plt.ylabel('Number of Stations')
plt.xticks(sorted(stations['JUMLAH BILANGAN UNIT PENGECAS'].unique()))
plt.show()

# Visualization 2: Proportion of AC vs DC Charger Bays
# Summing up AC and DC Charger Bays across all stations
total_ac_bays_stations = stations['AC BAY'].sum()
total_dc_bays_stations = stations['DC BAY'].sum()

bays_data_stations = {'Charger Type': ['AC Bays', 'DC Bays'], 'Count': [total_ac_bays_stations, total_dc_bays_stations]}
bays_df_stations = pd.DataFrame(bays_data_stations)

plt.figure(figsize=(8, 8))
plt.pie(bays_df_stations['Count'], labels=bays_df_stations['Charger Type'], autopct='%1.1f%%', startangle=90, colors=['skyblue', 'lightcoral'])
plt.title('Proportion of AC vs DC Charger Bays (Raw Data)')
plt.axis('equal') # Equal aspect ratio ensures that pie is drawn as a circle.
plt.show()

# Visualization 3: Distribution of Total Station Capacity (KW)
plt.figure(figsize=(10, 6))
sns.histplot(stations['KAPASITI PEPASANGAN (KW)'], bins=10, kde=True, color='purple')
plt.title('Distribution of Total Station Capacity (KW) (Raw Data)')
plt.xlabel('Total Station Capacity (KW)')
plt.ylabel('Number of Stations')
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("whitegrid")

# Visualization 4: Distribution of DC and AC Chargers
plt.figure(figsize=(14, 6))

plt.subplot(1, 2, 1)
sns.countplot(x='DC', data=stations, palette='viridis')
plt.title('Distribution of DC Chargers per Station (Raw Data)')
plt.xlabel('Number of DC Chargers')
plt.ylabel('Number of Stations')

plt.subplot(1, 2, 2)
sns.countplot(x='AC', data=stations, palette='magma')
plt.title('Distribution of AC Chargers per Station (Raw Data)')
plt.xlabel('Number of AC Chargers')
plt.ylabel('Number of Stations')

plt.tight_layout()
plt.show()

"""# **DATA CLEANING (OBJ 2)**"""

stations_drop = stations.drop(columns=['BIL.','NO. LESEN','TEMPOH SAH LESEN','NAMA PEMEGANG LESEN',])
stations_drop.head()

import re
import pandas as pd

def extract_ac_capacity(text):
    if pd.isna(text):
        return 0
    ac_total_capacity = 0
    # Regex to find (power) followed by 'KW AC', 'KWAC', 'AC' AND (number of units)
    pattern = r'(\d+\.?\d*)\s*KW?\s*AC(?::\s*(\d+)\s*UNIT(?:S)?)?'
    matches = re.findall(pattern, str(text), re.IGNORECASE)
    for match in matches:
        power = float(match[0])
        units_str = match[1] # Number of units, can be None if not found
        units = int(units_str) if units_str else 1 # Default to 1 unit if not specified
        ac_total_capacity += power * units
    return int(ac_total_capacity)

def extract_dc_capacity(text):
    if pd.isna(text):
        return 0
    dc_total_capacity = 0
    # Regex to find (power) followed by 'KW DC', 'KWDC', 'DC' AND (number of units)
    pattern = r'(\d+\.?\d*)\s*KW?\s*DC(?::\s*(\d+)\s*UNIT(?:S)?)?'
    matches = re.findall(pattern, str(text), re.IGNORECASE)
    for match in matches:
        power = float(match[0])
        units_str = match[1] # Number of units, can be None if not found
        units = int(units_str) if units_str else 1 # Default to 1 unit if not specified
        dc_total_capacity += power * units
    return int(dc_total_capacity)

import re
stations_drop['DC_Capacity_kW'] = stations_drop['KEUPAYAAN SETIAP UNIT PENGECAS'].apply(extract_dc_capacity)
stations_drop['AC_Capacity_kW'] = stations_drop['KEUPAYAAN SETIAP UNIT PENGECAS'].apply(extract_ac_capacity)

stations_drop[['KEUPAYAAN SETIAP UNIT PENGECAS', 'DC_Capacity_kW', 'AC_Capacity_kW']].head()

stations_drop[['KEUPAYAAN SETIAP UNIT PENGECAS','KAPASITI PEPASANGAN (KW)', 'AC_Capacity_kW', 'DC_Capacity_kW']]

# Example: manually setting values for specific rows
stations_drop.loc[0, ['AC_Capacity_kW', 'DC_Capacity_kW']] = [0, 50]
stations_drop.loc[1, ['AC_Capacity_kW', 'DC_Capacity_kW']] = [0, 44]
stations_drop.loc[2, ['AC_Capacity_kW', 'DC_Capacity_kW']] = [0, 180]
stations_drop.loc[8, ['AC_Capacity_kW', 'DC_Capacity_kW']] = [33, 0]
stations_drop.loc[12, ['AC_Capacity_kW', 'DC_Capacity_kW']] = [44, 0]

stations_drop.loc[13, ['AC_Capacity_kW', 'DC_Capacity_kW']] = [11,22]
stations_drop.loc[17, ['AC_Capacity_kW', 'DC_Capacity_kW']] = [204, 0]
stations_drop.loc[19, ['AC_Capacity_kW', 'DC_Capacity_kW']] = [14,0]
stations_drop.loc[21, ['AC_Capacity_kW', 'DC_Capacity_kW']] = [44, 0]
stations_drop.loc[26, ['AC_Capacity_kW', 'DC_Capacity_kW']] = [36, 0]

stations_drop.loc[27, ['AC_Capacity_kW', 'DC_Capacity_kW']] = [44,0]
stations_drop.loc[28, ['AC_Capacity_kW', 'DC_Capacity_kW']] = [44,0]
stations_drop.loc[30, ['AC_Capacity_kW', 'DC_Capacity_kW']] = [44,0]
stations_drop.loc[31, ['AC_Capacity_kW', 'DC_Capacity_kW']] = [22, 120]
stations_drop.loc[32, ['AC_Capacity_kW', 'DC_Capacity_kW']] = [0,240]
stations_drop.loc[33, ['AC_Capacity_kW', 'DC_Capacity_kW']] = [0,240]
stations_drop.loc[34, ['AC_Capacity_kW', 'DC_Capacity_kW']] = [44,0]
stations_drop.loc[35, ['AC_Capacity_kW', 'DC_Capacity_kW']] = [44,0]

stations_drop

stations_drop.columns

rename_mapping = {
    'Unnamed: 0': 'ID',
    'ALAMAT PEPASANGAN': 'Station Address',
    'KEUPAYAAN SETIAP UNIT PENGECAS': 'Charger Capacity per Unit',
    'JUMLAH BILANGAN UNIT PENGECAS': 'Total Number of Chargers',
    'KAPASITI PEPASANGAN (KW)': 'Total Station Capacity (KW)',
    'JUMLAH BAY': 'Total Charger Bays',
    'DC BAY': 'DC Charger Bays',
    'AC BAY': 'AC Charger Bays'
}

stations_new = stations_drop.rename(columns=rename_mapping)

stations_new.columns

stations_new

import re

def extract_postcode(address):
    # Malaysian postcodes are typically 5 digits
    match = re.search(r'\b(\d{5})\b', address)
    if match:
        return match.group(1)
    return None # Return None if no postcode is found

stations_new['Postcode'] = stations_new['Station Address'].apply(extract_postcode)
stations_new.head()

stations_new['Postcode'].value_counts()

kuantan_postcodes = ['25000', '25050', '25100', '25150', '25200', '25250', '25300', '25350', '26060', '26080', '26100', '26300', '25990']

print("Defined Kuantan Postcodes:", kuantan_postcodes)

kuantan_stations = stations_new[stations_new['Postcode'].isin(kuantan_postcodes)]
kuantan_stations

import numpy as np

kuantan_stations['Latitude'] = np.nan
kuantan_stations['Longitude'] = np.nan

kuantan_stations_for_manual_input = kuantan_stations[['ID', 'Station Address', 'Latitude', 'Longitude']]

import numpy as np

kuantan_stations['Latitude'] = np.nan
kuantan_stations['Longitude'] = np.nan

# Manually update a few rows with example Latitude and Longitude for demonstration
# These are example coordinates and may not be exact for the addresses
kuantan_stations.loc[kuantan_stations['ID'] == 3, ['Latitude', 'Longitude']] = [3.809554, 103.160203] # Mukim Hulu Lepar
kuantan_stations.loc[kuantan_stations['ID'] == 6, ['Latitude', 'Longitude']] = [3.841799328529357, 103.33686783830244] # BLH ECOENERGY SDN. BHD.
kuantan_stations.loc[kuantan_stations['ID'] == 25, ['Latitude', 'Longitude']] = [3.7180080498337285, 103.12495822379377] # PETRONAS R&R GAMBANG
kuantan_stations.loc[kuantan_stations['ID'] == 57, ['Latitude', 'Longitude']] = [3.815410601157337, 103.33012659980363] # BERJAYA MEGAMALL
kuantan_stations.loc[kuantan_stations['ID'] == 58, ['Latitude', 'Longitude']] = [3.797762016103057, 103.3220722152441] # HADAPAN BANGUNAN MBK

kuantan_stations_for_manual_input = kuantan_stations[['ID', 'Station Address', 'Latitude', 'Longitude']]
kuantan_stations_for_manual_input.head()

kuantan_stations.loc[kuantan_stations['ID'] == 59, ['Latitude', 'Longitude']] = [3.805868982826525, 103.3292651400137] # MEGAVIEW HOTEL
kuantan_stations.loc[kuantan_stations['ID'] == 96, ['Latitude', 'Longitude']] = [3.808833571940506, 103.3658595440147] # DINASOUR ENCOUNTER ZOO TERUNTUM
kuantan_stations.loc[kuantan_stations['ID'] == 116, ['Latitude', 'Longitude']] = [3.817343773064012, 103.3296588061276] # EMPIRE SEAFOOD RESTAURANT KUANTAN
kuantan_stations.loc[kuantan_stations['ID'] == 117, ['Latitude', 'Longitude']] = [3.815887887418381, 103.37210207777055] # LOTENG, JLN TENGKU ABU BAKAR
kuantan_stations.loc[kuantan_stations['ID'] == 118, ['Latitude', 'Longitude']] = [3.7992958104242676, 103.32255108465964] # MCDONALD'S KUANTAN RIVERFRONT
kuantan_stations.loc[kuantan_stations['ID'] == 124, ['Latitude', 'Longitude']] = [3.8285313704252695, 103.33958847479336] # KEMAMAN CUISINE
kuantan_stations.loc[kuantan_stations['ID'] == 127, ['Latitude', 'Longitude']] = [3.812494091683121, 103.37208295752383] # STARBUCKS, JALAN TENGKU ABU BAKAR
kuantan_stations.loc[kuantan_stations['ID'] == 163, ['Latitude', 'Longitude']] = [3.811546891901587, 103.37135657284689] # HYATT REGENCY KUANTAN
kuantan_stations.loc[kuantan_stations['ID'] == 169, ['Latitude', 'Longitude']] = [3.806343224093929, 103.32787516913339] # MAHKOTA SQUARE
kuantan_stations.loc[kuantan_stations['ID'] == 197, ['Latitude', 'Longitude']] = [3.8342650109189433, 103.29954654417546] # STARBUCKS INDERA MAHKOTA
kuantan_stations.loc[kuantan_stations['ID'] == 251, ['Latitude', 'Longitude']] = [3.7946785690853693, 103.31303084403778] # PESAT CTM
kuantan_stations.loc[kuantan_stations['ID'] == 270, ['Latitude', 'Longitude']] = [4.133541073121427, 103.39895301277285] # CHERATING POND
kuantan_stations.loc[kuantan_stations['ID'] == 271, ['Latitude', 'Longitude']] = [3.8194487001449007, 103.32605755753157] # THE ZENITH HOTEL
kuantan_stations.loc[kuantan_stations['ID'] == 301, ['Latitude', 'Longitude']] = [3.8480627034807817, 103.33727991904279] # YS AUTOWORLD
kuantan_stations.loc[kuantan_stations['ID'] == 338, ['Latitude', 'Longitude']] = [3.803190725043531, 103.33716628446318] # BAZAR SERAMBI TERUNTUM
kuantan_stations.loc[kuantan_stations['ID'] == 339, ['Latitude', 'Longitude']] = [3.8257556739192706, 103.30445944037535] # MCDONALD'S INDERA MAHKOTA
kuantan_stations.loc[kuantan_stations['ID'] == 422, ['Latitude', 'Longitude']] = [4.164229411294701, 103.41064957301059] # THE KASTURI RESORT CHERATING
kuantan_stations.loc[kuantan_stations['ID'] == 503, ['Latitude', 'Longitude']] = [3.79846805267836, 103.32195695767022] # BANGUNAN TEXAS, MAJLIS BANDARAYA KUANTAN
kuantan_stations.loc[kuantan_stations['ID'] == 646, ['Latitude', 'Longitude']] = [3.8103079968653355, 103.33103355216213] # JLN TELUK SISEK
kuantan_stations.loc[kuantan_stations['ID'] == 670, ['Latitude', 'Longitude']] = [3.911132596264498, 103.3653018423298] # BALOK BEACH
kuantan_stations.loc[kuantan_stations['ID'] == 940, ['Latitude', 'Longitude']] = [3.8559753864439483, 103.31972957485624] # PAHANG SKILLS DEVELOPMENT CENTRE
kuantan_stations.loc[kuantan_stations['ID'] == 947, ['Latitude', 'Longitude']] = [3.818593010403264, 103.32624279980357] # EAST COAST MALL
kuantan_stations.loc[kuantan_stations['ID'] == 948, ['Latitude', 'Longitude']] = [3.817929299100465, 103.32799159997151] # KUANTAN CITY MALL
kuantan_stations.loc[kuantan_stations['ID'] == 1015, ['Latitude', 'Longitude']] = [3.879600938255358, 103.36593771534038] # GERAI BATU HITAM
kuantan_stations.loc[kuantan_stations['ID'] == 1150, ['Latitude', 'Longitude']] = [3.8167776260257873, 103.33670999995282] # AC HOTEL KUANTAN
kuantan_stations.loc[kuantan_stations['ID'] == 1301, ['Latitude', 'Longitude']] = [3.8178817005428645, 103.32803607105998] # KUANTAN CITYMALL (duplicate address)
kuantan_stations.loc[kuantan_stations['ID'] == 1362, ['Latitude', 'Longitude']] = [3.8367929958139513, 103.30368354417547] # ONE SURIA
kuantan_stations.loc[kuantan_stations['ID'] == 1368, ['Latitude', 'Longitude']] = [3.819536701358897, 103.32740499857451] # KUALA KUANTAN
kuantan_stations.loc[kuantan_stations['ID'] == 1443, ['Latitude', 'Longitude']] = [3.8109110176242487, 103.32791866931922] # PERBADANAN KEMAJUAN PERTANIAN
kuantan_stations.loc[kuantan_stations['ID'] == 1727, ['Latitude', 'Longitude']] = [3.8711060740963243, 103.2746534171062] # TASEK COMMERCIAL CENTRE

kuantan_stations_for_manual_input = kuantan_stations[['ID', 'Station Address', 'Latitude', 'Longitude']]
kuantan_stations_for_manual_input

"""**Reasoning**:
The subtask of preparing the DataFrame for manual coordinate input and updating selected rows with example latitude and longitude values has been completed. Now, I will display the `kuantan_stations` DataFrame to review the manually updated latitude and longitude values.


"""

kuantan_stations

"""## Verify Manual Input

### Subtask:
Check if the 'Latitude' and 'Longitude' columns have been populated after manual input.

**Reasoning**:
To verify that the 'Latitude' and 'Longitude' columns have been populated after manual input, I will check the count of non-null values in both columns and compare them with the total number of rows in the `kuantan_stations` DataFrame.
"""

num_populated_latitude = kuantan_stations['Latitude'].notnull().sum()
num_populated_longitude = kuantan_stations['Longitude'].notnull().sum()
total_rows = len(kuantan_stations)

print(f"Number of populated Latitude values: {num_populated_latitude}")
print(f"Number of populated Longitude values: {num_populated_longitude}")
print(f"Total number of rows in kuantan_stations: {total_rows}")

if num_populated_latitude == total_rows and num_populated_longitude == total_rows:
    print("All 'Latitude' and 'Longitude' values have been populated.")
else:
    print("Some 'Latitude' or 'Longitude' values are still missing.")

kuantan_stations = kuantan_stations.drop(columns=['Charger Capacity per Unit'])
kuantan_stations['Station Address'] = kuantan_stations['Station Address'].str.title()
kuantan_stations.head()

"""## Visualize Charging Ports on Map

### Subtask:
Create an interactive map showing the location of each charging port in Kuantan using the manually provided geocoded data.

"""

import folium

# Calculate the mean latitude and longitude to center the map
mean_lat = kuantan_stations['Latitude'].mean()
mean_lon = kuantan_stations['Longitude'].mean()

# Create a Folium map centered at Kuantan
kuantan_map = folium.Map(location=[mean_lat, mean_lon], zoom_start=12)

# Add markers for each charging station
for index, row in kuantan_stations.iterrows():
    if pd.notnull(row['Latitude']) and pd.notnull(row['Longitude']):
        folium.Marker(
            location=[row['Latitude'], row['Longitude']],
            popup=f"<b>Address:</b> {row['Station Address']}<br><b>Total Chargers:</b> {row['Total Number of Chargers']}<br><b>DC Bays:</b> {row['DC Charger Bays']}<br><b>AC Bays:</b> {row['AC Charger Bays']}",
            icon=folium.Icon(color='blue', icon='charging-station', prefix='fa')
        ).add_to(kuantan_map)

# Display the map
kuantan_map

kuantan_stations.to_csv('kuantan_ev_stations.csv', index=False)
print("DataFrame successfully saved to 'kuantan_ev_stations.csv'")

"""**Create new column average charging hours per day**"""

ev = pd.read_csv('kuantan_ev_stations.csv')
ev.head()

import numpy as np

np.random.seed(1203)

# Average AC charging hours per day (4–8 hours)
ev['Avg_AC_Hours'] = np.where(
    ev['AC_Capacity_kW'] > 0,
    np.random.uniform(8,12, size=len(ev)),
    0
)

# Average DC charging hours per day (3–6 hours)
ev['Avg_DC_Hours'] = np.where(
    ev['DC_Capacity_kW'] > 0,
    np.random.uniform(2, 4, size=len(ev)),
    0
)

# Optional: round to 2 decimal places
ev['Avg_AC_Hours'] = ev['Avg_AC_Hours'].round(2)
ev['Avg_DC_Hours'] = ev['Avg_DC_Hours'].round(2)

# Drop the specified columns
ev = ev.drop(columns=['Avg_AC_Charging_Hours_Per_Day', 'Avg_DC_Charging_Hours_Per_Day'], errors='ignore')

ev.head(2)

"""**Calculating cost and revenue**

7kWh/22kWh AC Charging: RM0.55/kWh

180kWh DC Charging: RM1.00/kWh

350kWh DC Charging: RM1.20/kWh

source: https://soyacincau.com/2022/12/02/ev-dc-fast-charging-in-malaysia-gentari-kwh-vs-time-based-charging-which-is-cheaper/#:~:text=350kWh%20DC%20Charging:%20RM1.&text=The%20pricing%20for%20DC%20fast,to%20charge%20at%20these%20stations.
"""

# Define tariff rates
ac_rate = 0.55
dc_rate_180_kwh = 1.00 # For 180kWh DC Charging
dc_rate_350_kwh = 1.20 # For 350kWh DC Charging

# Calculate AC Revenue
# Using 'Avg_AC_Hours' from the ev DataFrame
ev['AC_revenue (RM)'] = (ev['AC_Capacity_kW'] * ev['Avg_AC_Hours'] * ac_rate).round(2)

# Calculate DC Revenue based on tiers
def calculate_dc_revenue_tiered(row):
    total_dc_capacity = row['DC_Capacity_kW']
    avg_dc_charging_hours = row['Avg_DC_Hours'] # Use Avg_DC_Hours

    if total_dc_capacity == 0:
        return 0.0
    # Apply RM1.00/kWh for DC capacity up to 180kW
    elif total_dc_capacity <= 180:
        return total_dc_capacity * avg_dc_charging_hours * dc_rate_180_kwh
    # Apply RM1.20/kWh for DC capacity greater than 180kW
    else:
        return total_dc_capacity * avg_dc_charging_hours * dc_rate_350_kwh

ev['DC_revenue (RM)'] = ev.apply(calculate_dc_revenue_tiered, axis=1).round(2)

# Display the relevant columns to verify the new calculations
ev[['Station Address', 'AC_Capacity_kW', 'DC_Capacity_kW', 'Avg_AC_Hours', 'Avg_DC_Hours', 'AC_revenue (RM)', 'DC_revenue (RM)']].head()

ev['Total_revenue (RM)'] = ev['AC_revenue (RM)'] + ev['DC_revenue (RM)']
ev[['Station Address', 'AC_revenue (RM)', 'DC_revenue (RM)', 'Total_revenue (RM)']].head()

ev

import folium

# Calculate the mean latitude and longitude to center the map
mean_lat = ev['Latitude'].mean()
mean_lon = ev['Longitude'].mean()

# Create a Folium map centered at Kuantan
kuantan_map = folium.Map(location=[mean_lat, mean_lon], zoom_start=12)

# Define revenue thresholds based on percentiles
low_threshold = ev['Total_revenue (RM)'].quantile(0.33)
medium_threshold = ev['Total_revenue (RM)'].quantile(0.66)

# Function to determine marker color based on total revenue
def get_revenue_color(revenue):
    if revenue >= medium_threshold:
        return 'green'  # High revenue
    elif revenue >= low_threshold:
        return 'blue'   # Medium revenue
    else:
        return 'red'    # Low revenue

# Add markers for each charging station
for index, row in ev.iterrows():
    if pd.notnull(row['Latitude']) and pd.notnull(row['Longitude']):
        revenue_color = get_revenue_color(row['Total_revenue (RM)'])
        folium.Marker(
            location=[row['Latitude'], row['Longitude']],
            popup=f"<b>Address:</b> {row['Station Address']}<br><b>Total Chargers:</b> {row['Total Number of Chargers']}<br><b>DC Bays:</b> {row['DC Charger Bays']}<br><b>AC Bays:</b> {row['AC Charger Bays']}<br><b>Total Revenue:</b> RM{row['Total_revenue (RM)']:.2f}",
            icon=folium.Icon(color=revenue_color, icon='charging-station', prefix='fa')
        ).add_to(kuantan_map)

# Display the map
kuantan_map

ev.to_csv('kuantan_ev_revenue.csv', index=False)