# -*- coding: utf-8 -*-
"""DSP Scheduling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h2wnXHHeFmgp3BFjvPHtLWlhz4FUgyzJ

# **EXPLORATORY DATA ANALYSIS (CLEANED DATA)**
"""

import pandas as pd

data = pd.read_csv ('kuantan_ev_revenue.csv')
data.head()

print(data.columns)



print("Shape of the DataFrame:", data.shape)
print("\nInformation about the DataFrame:")
data.info()

import numpy as np

print("1. Descriptive Statistics for Key Numerical Variables:")
print(data[[
    'Total Number of Chargers', 'DC', 'AC', 'Total Station Capacity (KW)',
    'DC_Capacity_kW', 'AC_Capacity_kW', 'Avg_AC_Hours', 'Avg_DC_Hours',
    'AC_revenue (RM)', 'DC_revenue (RM)', 'Total_revenue (RM)'
]].describe().round(2))

print("\n2. Top 5 Stations by Total Revenue (RM):")
print(data.nlargest(5, 'Total_revenue (RM)')[['Station Address', 'Total_revenue (RM)']])

import matplotlib.pyplot as plt
import seaborn as sns

columns_to_visualize = [
    'Total Number of Chargers', 'DC', 'AC',
    'Total Station Capacity (KW)', 'Total Charger Bays', 'DC Charger Bays',
    'AC Charger Bays', 'DC_Capacity_kW', 'AC_Capacity_kW',
    'Avg_AC_Hours', 'Avg_DC_Hours',
    'AC_revenue (RM)', 'DC_revenue (RM)', 'Total_revenue (RM)'
]

# 1. Histograms for key numerical distributions
plt.figure(figsize=(18, 12))
for i, col in enumerate(['Total Number of Chargers', 'Total Station Capacity (KW)', 'Total_revenue (RM)', 'Avg_AC_Hours', 'Avg_DC_Hours'], 1):
    plt.subplot(2, 3, i)
    sns.histplot(data[col], kde=True)
    plt.title(f'Distribution of {col}')
plt.tight_layout()
plt.show()

# 2. Scatter plot: Total Station Capacity (KW) vs Total_revenue (RM)
plt.figure(figsize=(10, 6))
sns.scatterplot(x='Total Station Capacity (KW)', y='Total_revenue (RM)', data=data)
plt.title('Total Revenue vs. Total Station Capacity')
plt.xlabel('Total Station Capacity (KW)')
plt.ylabel('Total Revenue (RM)')
plt.grid(True)
plt.show()

# 3. Bar plot: Total_revenue (RM) by Postcode
plt.figure(figsize=(12, 6))
revenue_by_postcode = data.groupby('Postcode')['Total_revenue (RM)'].sum().sort_values(ascending=False)
sns.barplot(x=revenue_by_postcode.index, y=revenue_by_postcode.values, palette='viridis')
plt.title('Total Revenue (RM) by Postcode')
plt.xlabel('Postcode')
plt.ylabel('Total Revenue (RM)')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# 4. Correlation Heatmap for numerical columns
plt.figure(figsize=(14, 10))
correlation_matrix = data[columns_to_visualize].corr()
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=.5)
plt.title('Correlation Matrix of Numerical Variables')
plt.tight_layout()
plt.show()

"""# **DATA PRE-PROCESSING (OBJ 2)**"""

data['Postcode'].unique()

population = pd.read_csv('population_dun.csv')
population.head()

kuantan_pop = population[population['state'].str.contains('Pahang', case=False, na=False)]
kuantan_pop

kuantan_pop_2022 = kuantan_pop[kuantan_pop['date'].str.contains('2022', na=False)]
kuantan_pop_2022 = kuantan_pop_2022[(kuantan_pop_2022['sex'] == 'both') & (kuantan_pop_2022['ethnicity'] == 'overall')]
kuantan_pop_2022

"""# Task
Create a DataFrame by merging the `kuantan_data` with a Postcode-DUN mapping (generated from a predefined list), and then merge the result with the `kuantan_pop_2022` DataFrame on the 'dun' column to include population data. Finally, display the head of the merged DataFrame.

## Create Postcode-DUN mapping

### Subtask:
Generate a DataFrame that maps Postcodes to their corresponding DUNs, using the provided list and ensuring DUN names match the format in `kuantan_pop_2022`.

**Reasoning**:
I will create a dictionary with the provided postcode-DUN mapping, convert it into a DataFrame, and name the columns as specified in the instructions.
"""

postcode_dun_mapping_dict = {
    26300: 'N.18 Lepar',
    25300: 'N.19 Panching',
    25150: 'N.14 Teruntum',
    25000: 'N.14 Teruntum',
    25100: 'N.14 Teruntum',
    25050: 'N.14 Teruntum',
    25250: 'N.15 Tanjung Lumpur',
    25200: 'N.13 Semambu',
    26080: 'N.17 Sungai Lembing',
    25350: 'N.13 Semambu',
    26060: 'N.18 Lepar',
    26100: 'N.17 Sungai Lembing',
    25990: 'N.16 Inderapura'
}

postcode_dun_df = pd.DataFrame(list(postcode_dun_mapping_dict.items()), columns=['Postcode', 'dun'])
postcode_dun_df

"""**Reasoning**:
I will merge the `data` DataFrame (which represents `kuantan_data`) with the `postcode_dun_df` DataFrame on the common 'Postcode' column. Then, I will merge the resulting DataFrame with `kuantan_pop_2022` on the 'dun' column to include population data. Finally, I will display the head of the fully merged DataFrame.


"""

merged_data = pd.merge(data, postcode_dun_df, on='Postcode', how='left')
final_merged_df = pd.merge(merged_data, kuantan_pop_2022, on='dun', how='left')
final_merged_df.head()

"""## Summary:

### Data Analysis Key Findings
*   A mapping DataFrame, `postcode_dun_df`, was successfully created, linking specific Postcodes to their corresponding DUN (Dewan Undangan Negeri) areas based on a predefined dictionary.
*   The initial `kuantan_data` was merged with the `postcode_dun_df` using the 'Postcode' column, successfully associating each data entry with its respective DUN.
*   The resulting DataFrame was then further merged with `kuantan_pop_2022` on the 'dun' column, effectively incorporating population data for each DUN into the dataset.
*   The final merged DataFrame, `final_merged_df`, now contains combined information from `kuantan_data`, the Postcode-DUN mapping, and the `kuantan_pop_2022` dataset, including 'dun' and 'population' columns.

### Insights or Next Steps
*   The `final_merged_df` provides a rich dataset that can be used for spatial analysis, allowing for the examination of trends or characteristics at the DUN level, factoring in population density.
*   Further analysis can be performed on this integrated dataset to identify correlations between various data points (from the original `kuantan_data`) and demographic information at the DUN level.

"""

final_merged_df = final_merged_df.drop(columns=['dun', 'date', 'state', 'parlimen', 'sex', 'age', 'ethnicity'])
final_merged_df

print(final_merged_df[['Station Address', 'population']].to_string())

import folium

# Calculate the mean latitude and longitude to center the map
mean_lat = final_merged_df['Latitude'].mean()
mean_lon = final_merged_df['Longitude'].mean()

# Create a Folium map centered at Kuantan
kuantan_map = folium.Map(location=[mean_lat, mean_lon], zoom_start=12)

# Function to determine marker color based on population
def get_population_color(population):
    if population < 50:
        return 'red'   # Low population
    elif 50 <= population < 100:
        return 'blue'  # Medium population
    else:
        return 'green' # High population

# Add markers for each charging station
for index, row in final_merged_df.iterrows():
    if pd.notnull(row['Latitude']) and pd.notnull(row['Longitude']):
        color = get_population_color(row['population'])

        # Create custom popup label
        popup_html = f"<b>Station Address:</b> {row['Station Address']}<br>" \
                     f"<b>Total Revenue:</b> RM {row['Total_revenue (RM)']:.2f}<br>" \
                     f"<b>Population (x1000):</b> {row['population']:.1f}<br>" \
                     f"<b>AC Charger Bays:</b> {int(row['AC Charger Bays'])}<br>" \
                     f"<b>DC Charger Bays:</b> {int(row['DC Charger Bays'])}"

        folium.Marker(
            location=[row['Latitude'], row['Longitude']],
            popup=popup_html,
            icon=folium.Icon(color=color, icon='info', prefix='fa') # Using 'info' icon as 'charging-station' does not support color directly
        ).add_to(kuantan_map)

# Display the map
kuantan_map

import folium

# Calculate the mean latitude and longitude to center the map
mean_lat = final_merged_df['Latitude'].mean()
mean_lon = final_merged_df['Longitude'].mean()

# Create a Folium map centered at Kuantan
kuantan_map_revenue = folium.Map(location=[mean_lat, mean_lon], zoom_start=12)

# Function to determine marker color based on revenue
def get_revenue_color(revenue):
    if revenue < 150:      # Example thresholds for revenue
        return 'red'   # Low revenue
    elif 150 <= revenue < 300:
        return 'blue'  # Medium revenue
    else:
        return 'green' # High revenue

# Add markers for each charging station
for index, row in final_merged_df.iterrows():
    if pd.notnull(row['Latitude']) and pd.notnull(row['Longitude']):
        color = get_revenue_color(row['Total_revenue (RM)'])

        # Create custom popup label
        popup_html = f"<b>Station Address:</b> {row['Station Address']}<br>" \
                     f"<b>Total Revenue:</b> RM {row['Total_revenue (RM)']:.2f}<br>" \
                     f"<b>Population (x1000):</b> {row['population']:.1f}<br>" \
                     f"<b>AC Charger Bays:</b> {int(row['AC Charger Bays'])}<br>" \
                     f"<b>DC Charger Bays:</b> {int(row['DC Charger Bays'])}"

        folium.Marker(
            location=[row['Latitude'], row['Longitude']],
            popup=popup_html,
            icon=folium.Icon(color=color, icon='charging-station', prefix='fa')
        ).add_to(kuantan_map_revenue)

# Display the map
kuantan_map_revenue

final_merged_df

final_merged_df.columns

"""ADT data generation"""

import numpy as np
np.random.seed(2111)

def generate_adt(population):
    if population < 25:
        return np.random.randint(8000, 15001)
    elif 25 <= population < 60:
        return np.random.randint(15000, 30001)
    elif 60 <= population < 120:
        return np.random.randint(30000, 50001)
    else:
        return np.random.randint(50000, 80001)

final_merged_df["ADT"] = final_merged_df["population"].apply(generate_adt)

if 'ADT_synthetic' in final_merged_df.columns:
    final_merged_df = final_merged_df.drop(columns=['ADT_synthetic'])
    print("Removed 'ADT_synthetic' column.")
else:
    print("'ADT_synthetic' column not found in final_merged_df. No action taken.")

final_data = final_merged_df
final_data

"""# **OPTIMIZING EV CHARGING SCHEDULING (OBJ 3)**

## 1. Peak hour data generation
"""

URBAN_KEYWORDS = [
    "city", "mall", "bandar", "pusat", "square", "komersial",
    "commercial", "downtown", "indera mahkota", "kuantan city"
]

def is_urban(address):
    address = address.lower()
    return any(keyword in address for keyword in URBAN_KEYWORDS)

# Peak hour flag generator
# -----------------------------
def peak_hour(row):
    urban = is_urban(row["Station Address"])
    pop = row["population"]
    adt = row["ADT"]  # or use real ADT if available

    if urban and (pop >= 60 or adt >= 30000):
        return "Yes"
    else:
        return "No"

final_data["Peak_Hour"] = final_data.apply(peak_hour, axis=1)
final_data

final_data[['Station Address', 'Avg_AC_Hours', 'Avg_DC_Hours', 'Total_revenue (RM)', 'ADT', 'Peak_Hour']]

final_data.to_csv('final_data.csv', index=False)

"""## 2. Machine Learning method

## Spatially Aware / Geospatial ML
"""

# Utilization proxy (used as target)
final_merged_df["utilization_score"] = final_merged_df["Total_revenue (RM)"] / final_merged_df["Total Station Capacity (KW)"]

final_merged_df

"""CatBoost"""

pip install catboost

from catboost import CatBoostRegressor
from sklearn.model_selection import train_test_split

"""Random Forest"""

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

X = final_merged_df[
    [
        "Total Charger Bays",
        "AC",
        "DC",
        "Total Station Capacity (KW)",
        "population"
    ]
]

y = final_merged_df["utilization_score"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = RandomForestRegressor(n_estimators=200, random_state=42)
model.fit(X_train, y_train)

final_merged_df["predicted_demand"] = model.predict(X)

from sklearn.metrics import mean_squared_error, r2_score
import numpy as np
y_pred = model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
print("RMSE:", np.sqrt(mse))
print("R²:", r2_score(y_test, y_pred))

import numpy as np

final_merged_df["queue_level"] = pd.qcut(
    final_merged_df["predicted_demand"],
    q=3,
    labels=["Low", "Medium", "High"]
)

def scheduling_decision(row):
    if row["queue_level"] == "High":
        return "Delay AC, Prioritize DC, Off-peak only"
    elif row["queue_level"] == "Medium":
        return "Limited AC charging"
    else:
        return "Normal operation"

final_merged_df["scheduling_action"] = final_merged_df.apply(scheduling_decision, axis=1)

final_merged_df [['Station Address','scheduling_action']]

"""## 3. MILP method"""

from pulp import LpProblem, LpMinimize, LpVariable

model = LpProblem("EV_Charging_Scheduling", LpMinimize)

stations = final_merged_df.index.tolist()
time_slots = ["peak", "off_peak"]

x = LpVariable.dicts("x", (stations, time_slots), cat="Binary")

# Objective
model += sum(
    final_merged_df.loc[s, "predicted_demand"] * x[s][t]
    for s in stations
    for t in time_slots
)

from pulp import (
    LpProblem,
    LpMinimize,
    LpVariable,
    lpSum,
    LpBinary
)

model_milp = LpProblem("EV_Charging_Scheduling", LpMinimize)

stations = final_merged_df.index.tolist()

x = LpVariable.dicts(
    "schedule",
    (stations, time_slots),
    cat=LpBinary
)

model_milp += lpSum(
    final_merged_df.loc[s, "predicted_demand"] * x[s][t]
    for s in stations
    for t in time_slots
)

for s in stations:
    for t in time_slots:
        model_milp += (
            final_merged_df.loc[s, "predicted_demand"] * x[s][t]
            <= final_merged_df.loc[s, "Total Station Capacity (KW)"]
        )

GRID_LIMIT = final_merged_df["Total Station Capacity (KW)"].sum() * 0.6

for t in time_slots:
    model_milp += lpSum(
        final_merged_df.loc[s, "predicted_demand"] * x[s][t]
        for s in stations
    ) <= GRID_LIMIT

for s in stations:
    model_milp += lpSum(
        x[s][t] for t in time_slots
    ) >= 1

model_milp.solve()

schedule_output = []

for s in stations:
    for t in time_slots:
        if x[s][t].value() == 1:
            schedule_output.append({
                "Station_ID": s,
                "Time_Slot": t
            })

schedule_df = pd.DataFrame(schedule_output)

final_merged_df["scheduled_peak"] = [
    int(x[s]["peak"].value()) for s in stations
]

final_merged_df["scheduled_off_peak"] = [
    int(x[s]["off_peak"].value()) for s in stations
]

def interpret(row):
    if row["scheduled_peak"] == 0 and row["scheduled_off_peak"] == 1:
        return "Off-peak only (Load shifting)"
    elif row["scheduled_peak"] == 1 and row["scheduled_off_peak"] == 1:
        return "Normal operation"
    else:
        return "Restricted operation"

final_merged_df["scheduling_decision"] = final_merged_df.apply(interpret, axis=1)

final_merged_df[
    [
        "Station Address",
        "predicted_demand",
        "scheduled_peak",
        "scheduled_off_peak",
        "scheduling_decision"
    ]
].head(10)

"""## 4. Evaluation"""

# Compute average-to-peak demand ratio per time slot
evaluation = {}
for t in time_slots:
    total_demand = sum(final_merged_df.loc[s, "predicted_demand"] * x[s][t].value() for s in stations)
    peak_demand = final_merged_df["predicted_demand"].max()
    evaluation[f"{t}_avg_to_peak_ratio"] = total_demand / peak_demand

# Compute % of stations meeting demand
satisfied_stations = len(schedule_df['Station_ID'].unique())
num_stations = len(stations)
evaluation["station_satisfaction"] = satisfied_stations / num_stations * 100

print("\nMILP Evaluation Metrics:")
for k, v in evaluation.items():
    print(f"{k}: {v:.2f}")

"""## Summary:

### Data Analysis Key Findings

*   A CatBoostRegressor model was successfully trained using 'Total Charger Bays', 'AC', 'DC', 'Total Station Capacity (KW)', and 'population' as features to predict 'utilization\_score'.
*   The trained CatBoostRegressor model achieved a Root Mean Squared Error (RMSE) of approximately 0.821 and an R-squared (R²) score of approximately 0.554 on the test set.
*   The model generated utilization predictions for the entire dataset, which were added as a new column `predicted_utilization_catboost` to `final_merged_df`.
*   These predicted utilization scores were further categorized into 'Low', 'Medium', and 'High' queue levels based on quantiles and stored in a new column `queue_level_catboost`.

### Insights or Next Steps

*   The CatBoostRegressor model explains about 55.4% of the variance in utilization scores, indicating a moderate predictive power. Further feature engineering or hyperparameter tuning could potentially improve model performance.
*   The categorized queue levels (`Low`, `Medium`, `High`) based on predicted utilization can be used for strategic planning, such as optimizing charger maintenance schedules, allocating resources, or identifying areas for new charger installations.

"""

final_merged_df

